import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate {

  private var flutterEngine: FlutterEngine?

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    // Start Flutter engine explicitly so the messenger is live before plugin registration
    let engine = FlutterEngine(name: "main_engine")
    engine.run()
    flutterEngine = engine

    // Use SafePluginRegistrant — NOT GeneratedPluginRegistrant.
    // GeneratedPluginRegistrant is regenerated by Flutter tools every build and contains
    // Swift plugins that crash with swift_getObjectType on iOS 26.
    // SafePluginRegistrant is our stable file that only registers ObjC plugins.
    SafePluginRegistrant.register(with: engine)

    // SharedPreferences: ObjC replacement for the Swift plugin (uses NSUserDefaults)
    if let registrar = engine.registrar(forPlugin: "SharedPreferencesPlugin") {
      SharedPreferencesObjCPlugin.register(with: registrar)
    }

    // Build the window programmatically
    window = UIWindow(frame: UIScreen.main.bounds)
    window?.rootViewController = FlutterViewController(engine: engine, nibName: nil, bundle: nil)
    window?.makeKeyAndVisible()

    return true
  }
}
