// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXjpjjSHDmA4RefMWFKKPJnIVWQytuR8s',
    appId: '1:907690538063:web:8cc712caefc3cc3ad9263a',
    messagingSenderId: '907690538063',
    projectId: 'truck-union-vendor',
    authDomain: 'truck-union-vendor.firebaseapp.com',
    storageBucket: 'truck-union-vendor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXjpjjSHDmA4RefMWFKKPJnIVWQytuR8s',
    appId: '1:907690538063:android:8cc712caefc3cc3ad9263a',
    messagingSenderId: '907690538063',
    projectId: 'truck-union-vendor',
    storageBucket: 'truck-union-vendor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVV1LaY05L0304a9pV7dtjaJ2khV4PULQ',
    appId: '1:907690538063:ios:0a08b9d86fedd3bbd9263a',
    messagingSenderId: '907690538063',
    projectId: 'truck-union-vendor',
    storageBucket: 'truck-union-vendor.firebasestorage.app',
    iosBundleId: 'com.abraglobal.abraVendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVV1LaY05L0304a9pV7dtjaJ2khV4PULQ',
    appId: '1:907690538063:ios:0a08b9d86fedd3bbd9263a',
    messagingSenderId: '907690538063',
    projectId: 'truck-union-vendor',
    storageBucket: 'truck-union-vendor.firebasestorage.app',
    iosBundleId: 'com.abraglobal.abraVendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXjpjjSHDmA4RefMWFKKPJnIVWQytuR8s',
    appId: '1:907690538063:web:8cc712caefc3cc3ad9263a',
    messagingSenderId: '907690538063',
    projectId: 'truck-union-vendor',
    authDomain: 'truck-union-vendor.firebaseapp.com',
    storageBucket: 'truck-union-vendor.firebasestorage.app',
  );
}
