-- Create customer_orders table (same as Abra Logistics)
CREATE TABLE IF NOT EXISTS `customer_orders` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firebase_uid VARCHAR(255) NOT NULL,
    tracking_number VARCHAR(100) NOT NULL UNIQUE,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    sender_name VARCHAR(255) NOT NULL,
    sender_mobile VARCHAR(20) NOT NULL,
    sender_address TEXT NOT NULL,
    receiver_name VARCHAR(255) NOT NULL,
    receiver_mobile VARCHAR(20) NOT NULL,
    receiver_address TEXT NOT NULL,
    origin_pincode VARCHAR(10) NOT NULL,
    dest_pincode VARCHAR(10) NOT NULL,
    route VARCHAR(255) NOT NULL,
    shipping_amount DECIMAL(10,2) NOT NULL,
    payment_mode ENUM('cod', 'prepaid') NOT NULL,
    payment_id VARCHAR(255) NULL,
    order_id VARCHAR(255) NULL,
    freight_type VARCHAR(50) DEFAULT 'road',
    load_type VARCHAR(50) DEFAULT 'part_load',
    speed_type VARCHAR(50) DEFAULT 'standard',
    vehicle_type VARCHAR(100) DEFAULT '',
    actual_weight VARCHAR(20) DEFAULT '1',
    courier VARCHAR(100) DEFAULT 'TRUCK UNION',
    status VARCHAR(50) DEFAULT 'AWB Created',
    book_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    ciudad VARCHAR(100) DEFAULT '',
    city1 VARCHAR(100) DEFAULT '',
    shipping_subtotal DECIMAL(10,2) DEFAULT 0,
    cod_total DECIMAL(10,2) NULL,
    
    -- Driver Assignment Fields
    vehicle_id INT NULL,
    driver_name VARCHAR(255) NULL,
    assigned_at TIMESTAMP NULL,
    picked_up_at TIMESTAMP NULL,
    delivered_at TIMESTAMP NULL,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_firebase_uid (firebase_uid),
    INDEX idx_tracking_number (tracking_number),
    INDEX idx_status (status),
    INDEX idx_book_date (book_date),
    INDEX idx_vehicle_id (vehicle_id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
